namespace AntiDupl.NET.Core.Enums
{
    public enum SortType
    {
        ByType = 0,
        BySortedPath = 1,
        BySortedName = 2,
        BySortedDirectory = 3,
        BySortedSize = 4,
        BySortedTime = 5,
        BySortedType = 6,
        BySortedWidth = 7,
        BySortedHeight = 8,
        BySortedArea = 9,
        BySortedRatio = 10,
        BySortedBlockiness = 11,
        BySortedBlurring = 12,
        ByFirstPath = 13,
        ByFirstName = 14,
        ByFirstDirectory = 15,
        ByFirstSize = 16,
        ByFirstTime = 17,
        ByFirstType = 18,
        ByFirstWidth = 19,
        ByFirstHeight = 20,
        ByFirstArea = 21,
        ByFirstRatio = 22,
        ByFirstBlockiness = 23,
        ByFirstBlurring = 24,
        BySecondPath = 25,
        BySecondName = 26,
        BySecondDirectory = 27,
        BySecondSize = 28,
        BySecondTime = 29,
        BySecondType = 30,
        BySecondWidth = 31,
        BySecondHeight = 32,
        BySecondArea = 33,
        BySecondRatio = 34,
        BySecondBlockiness = 35,
        BySecondBlurring = 36,
        ByDefect = 37,
        ByDifference = 38,
        ByTransform = 39,
        ByGroup = 40,
        ByGroupSize = 41,
        ByHint = 42,
    }
}
